version: "3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - ./config:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
